### ISSUE TITLE
Build crashes after upgrading v0.0.34-alpha1 to v0.0.37-alpha12

### ISSUE THREAD

**Issue by pospi** [holochain/holochain-rust#1846] opened 2019-11-08 01:18 UTC
Since this upgrade I am getting *"Error: Couldn't create a DNA from the bundle, got error missing field `code`"* when attempting to build. I've purged the repo with the Holonix `hn-flush` command and am still experiencing the issue.

**Comment by guillemcordoba** [comment] 2019-11-08 21:13
Same error here, when updating from v0.0.30-alpha7 to v0.0.37-alpha12.

**Comment by willemolding** [comment] 2019-11-11 00:15
Hey @pospi could you give some steps to recreate the issue. We made some changes to how the .dna.json file is parsed and this might be what is causing it. 

It also might be worth checking that there are no `__META__` fields inside the `zomes` field of the .dna.json or building with the `hc package --strip-meta` to see if this makes a difference.

**Comment by willemolding** [comment] 2019-11-11 00:38
Ok I can confirm that using `hc package --strip-meta` lets you build without issue. The issue is related to `__META__` fields inside the zome object being treated as zomes which require code. You can use this fix until the next release

**Comment by willemolding** [comment] 2019-11-13 00:03
This should be fixed in the next release. I'll wait for a confirmation and then close the issue.

**Comment by guillemcordoba** [comment] 2019-11-13 12:15
Can confirm the issue is gone! Now compiling and running fine. But I did have to replace all `.hcbuild` files on all zomes for the new ones from https://github.com/holochain/holochain-rust/blob/develop/app_spec/zomes/blog/code/.hcbuild.

Thanks for the hard work, keep it up!

**Closed** 2019-12-02 22:53 UTC
